server:
  port: 8090
spring:
  application:
    name: apige

  cloud:
    gateway:
      routes:
        - id: ui
          uri: http://localhost:8082/
          Predicates:
            - Path=/ui/**
          filters:
            - RewritePath=/ui/(?<segment>.*), /$\{segment}
        - id: recommendations
          uri: http://localhost:8081/
          Predicates:
            - Path=/recommendations/**
        - id: payments
          uri: http://localhost:8083/
          Predicates:
            - Path=/catalog/**
#        - id: notifications
#          uri: http://localhost:8081/
#          Predicates:
#            - Path=/notifications/**
#        - id: cart
#          uri: http://localhost:8081/
#          Predicates:
#            - Path=/cart/**
#        - id: search
#          uri: http://localhost:8081/
#          Predicates:
#            - Path=/search/**
#