spring:
  application:
    name: stock
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:admin}
    url: ${MYSQL_URL:jdbc:mysql://localhost:3306/myDb?createDatabaseIfNotExist=true}
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          create_namespaces: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}


