on:
  push:
    branches: [ master ]
    paths:
      - 'catalog-service/**'
      - '.github/workflows/catalog-service.yml'

permissions:
  checks: write
  pull-requests: write
  packages: write

jobs:
  test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: test
        run:
          echo ${{ github.event.head_commit.modified }}
  build-catalog-service:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'temurin'

      - name: Package artifact
        run: |
          cd catalog-service
          mvn clean package

      - name: Publish Test Report
        if: success() || failure()
        uses: scacap/action-surefire-report@v1

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          file: ./Dockerfile
          registry: https://ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}